/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loja.ui;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import loja.negocio.Marca;
import loja.negocio.Sistema;

/**
 *
 * @author Daniel
 */
public class CRUDMarca extends javax.swing.JDialog {

    private final Sistema sis;
    
    /**
     * Creates new form CRUDMarca
     * @param parent
     * @param modal
     */
    public CRUDMarca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        sis = Sistema.getInstance();
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tbListarMarca.getModel();
        tbListarMarca.setRowSorter(new TableRowSorter(modelo));
        carregarMarcas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListarMarca = new javax.swing.JTable();
        tfRepresentante = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jNovo = new javax.swing.JMenu();
        jEditar = new javax.swing.JMenu();
        jExcluir = new javax.swing.JMenu();
        jSalvar = new javax.swing.JMenu();
        jCancelar = new javax.swing.JMenu();
        jSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome da Marca");

        tfNome.setEnabled(false);

        jLabel2.setText("Representante Comercial");

        tbListarMarca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome da Marca", "Representante Comercial"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbListarMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListarMarcaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbListarMarca);

        tfRepresentante.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tfRepresentante))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/page_white_add.png"))); // NOI18N
        jNovo.setText("Novo");
        jNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNovoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jNovoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jNovoMouseExited(evt);
            }
        });
        jMenuBar1.add(jNovo);

        jEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/page_edit.png"))); // NOI18N
        jEditar.setText("Editar");
        jEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jEditarMouseExited(evt);
            }
        });
        jMenuBar1.add(jEditar);

        jExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/page_delete.png"))); // NOI18N
        jExcluir.setText("Excluir");
        jExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExcluirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jExcluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jExcluirMouseExited(evt);
            }
        });
        jMenuBar1.add(jExcluir);

        jSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table_save.png"))); // NOI18N
        jSalvar.setText("Salvar");
        jSalvar.setEnabled(false);
        jSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSalvarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jSalvarMouseExited(evt);
            }
        });
        jMenuBar1.add(jSalvar);

        jCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        jCancelar.setText("Cancelar");
        jCancelar.setEnabled(false);
        jCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCancelarMouseExited(evt);
            }
        });
        jMenuBar1.add(jCancelar);

        jSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/link_go.png"))); // NOI18N
        jSair.setText("Sair");
        jSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jSairMouseExited(evt);
            }
        });
        jMenuBar1.add(jSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNovoMouseClicked
        // TODO add your handling code here:
        jNovo.setEnabled(false);
        jSalvar.setEnabled(true);
        jCancelar.setEnabled(true);
        tfNome.setEnabled(true);
        tfRepresentante.setEnabled(true);
    }//GEN-LAST:event_jNovoMouseClicked

    private void jNovoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNovoMouseEntered
        // TODO add your handling code here:
        jNovo.setForeground(Color.red);
    }//GEN-LAST:event_jNovoMouseEntered

    private void jNovoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNovoMouseExited
        // TODO add your handling code here:
        jNovo.setForeground(Color.black);
    }//GEN-LAST:event_jNovoMouseExited

    private void jEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEditarMouseClicked
        // TODO add your handling code here:
        try {
            boolean ok = true;
            if (tfNome.getText().equals("")) {
                ok = false;
                tfNome.setBackground(Color.PINK);
            } else {
                tfNome.setBackground(Color.WHITE);
            }
            if (tfRepresentante.getText().equals("")) {
                ok = false;
                tfRepresentante.setBackground(Color.PINK);
            } else {
                tfRepresentante.setBackground(Color.WHITE);
            }
            if (ok) {
                String nome = tfNome.getText();
                String representante = tfRepresentante.getText();
                Marca marca = new Marca(nome, representante);
                int cod = (int) tbListarMarca.getValueAt(tbListarMarca.getSelectedRow(), 0);
                marca.setId(cod);
                if (sis.alterarMarca(marca, cod)) {
                    JOptionPane.showMessageDialog(this, "Produto Alterado com Sucesso!");
                    carregarMarcas();
                } else {
                    JOptionPane.showMessageDialog(this, "O Produto não foi Alterado!");
                    carregarMarcas();
                }
                reiniciarMenu();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Falha ao Alterar o Produto");
        }
    }//GEN-LAST:event_jEditarMouseClicked

    private void jEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEditarMouseEntered
        // TODO add your handling code here:
        jEditar.setForeground(Color.red);
    }//GEN-LAST:event_jEditarMouseEntered

    private void jEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEditarMouseExited
        // TODO add your handling code here:
        jEditar.setForeground(Color.black);
    }//GEN-LAST:event_jEditarMouseExited

    private void jExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExcluirMouseClicked
        // TODO add your handling code here:
        try {
            int cod = (int) tbListarMarca.getValueAt(tbListarMarca.getSelectedRow(), 0);
            if (sis.excluirMarca(cod)) {
                JOptionPane.showMessageDialog(this, "Item excluído com sucesso!");
                carregarMarcas();
                reiniciarMenu();
            } else {
                JOptionPane.showMessageDialog(this, "Falha ao excluir!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Selecione algum registro da tabela");
        }
    }//GEN-LAST:event_jExcluirMouseClicked

    private void jExcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExcluirMouseEntered
        // TODO add your handling code here:
        jExcluir.setForeground(Color.red);
    }//GEN-LAST:event_jExcluirMouseEntered

    private void jExcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExcluirMouseExited
        // TODO add your handling code here:
        jExcluir.setForeground(Color.black);
    }//GEN-LAST:event_jExcluirMouseExited

    private void jSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSalvarMouseClicked
        // TODO add your handling code here:
        boolean ok = true;
        if (tfNome.getText().equals("")) {
            ok = false;
            tfNome.setBackground(Color.PINK);
        } else {
            tfNome.setBackground(Color.WHITE);
        }
        if (tfRepresentante.getText().equals("")) {
            ok = false;
            tfRepresentante.setBackground(Color.PINK);
        } else {
            tfRepresentante.setBackground(Color.WHITE);
        }
        if (ok) {
            String nome = tfNome.getText();
            String representante = tfRepresentante.getText();
            Marca marca = new Marca(nome, representante);
            if (sis.inserirMarca(marca)) {
                JOptionPane.showMessageDialog(this, "Produto Inserido com Sucesso!");
                carregarMarcas();
            } else {
                JOptionPane.showMessageDialog(this, "O Produto não foi Inserido!");
                carregarMarcas();
            }
            reiniciarMenu();
        }
    }//GEN-LAST:event_jSalvarMouseClicked

    private void jSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSalvarMouseEntered
        // TODO add your handling code here:
        jSalvar.setForeground(Color.red);
    }//GEN-LAST:event_jSalvarMouseEntered

    private void jSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSalvarMouseExited
        // TODO add your handling code here:
        jSalvar.setForeground(Color.black);
    }//GEN-LAST:event_jSalvarMouseExited

    private void jCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCancelarMouseClicked
        // TODO add your handling code here:
        reiniciarMenu();
    }//GEN-LAST:event_jCancelarMouseClicked

    private void jCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCancelarMouseEntered
        // TODO add your handling code here:
        jCancelar.setForeground(Color.red);
    }//GEN-LAST:event_jCancelarMouseEntered

    private void jCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCancelarMouseExited
        // TODO add your handling code here:
        jCancelar.setForeground(Color.black);
    }//GEN-LAST:event_jCancelarMouseExited

    private void jSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSairMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jSairMouseClicked

    private void jSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSairMouseEntered
        // TODO add your handling code here:
        jSair.setForeground(Color.red);
    }//GEN-LAST:event_jSairMouseEntered

    private void jSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSairMouseExited
        // TODO add your handling code here:
        jSair.setForeground(Color.black);
    }//GEN-LAST:event_jSairMouseExited

    private void tbListarMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListarMarcaMouseClicked
        // TODO add your handling code here:
        try {
            jNovo.setEnabled(true);
            jSalvar.setEnabled(false);
            jCancelar.setEnabled(true);
            tfNome.setEnabled(true);
            tfRepresentante.setEnabled(true);
            tfNome.setText((String) tbListarMarca.getValueAt(tbListarMarca.getSelectedRow(), 1));
            String replace = (String) tbListarMarca.getValueAt(tbListarMarca.getSelectedRow(), 2);
           tfRepresentante.setText(replace);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_tbListarMarcaMouseClicked

    
      private void carregarMarcas() {
        ArrayList<Marca> marcas = (ArrayList<Marca>) sis.listarMarca();
        DefaultTableModel modelo = (DefaultTableModel) tbListarMarca.getModel();
        modelo.setNumRows(0);
        marcas.forEach((_item) -> {
            modelo.addRow(new Object[]{
                _item.getId(),
                _item.getNome(),
                _item.getRepresentanteComercial(),
            });
        });
    }

       private void reiniciarMenu() {
        tfNome.setEnabled(false);
        tfNome.setText("");
        tfRepresentante.setEnabled(false);
        tfRepresentante.setText("");
        jNovo.setEnabled(true);
        jSalvar.setEnabled(false);
        jCancelar.setEnabled(false);
        tfNome.setBackground(Color.white);
        tfRepresentante.setBackground(Color.white);
        tfNome.setBackground(Color.white);
    }
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jCancelar;
    private javax.swing.JMenu jEditar;
    private javax.swing.JMenu jExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jNovo;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenu jSair;
    private javax.swing.JMenu jSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbListarMarca;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfRepresentante;
    // End of variables declaration//GEN-END:variables
}
