/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loja.ui;

import javax.swing.JOptionPane;
import loja.negocio.Sistema;

/**
 *
 * @author Daniel
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private final String tipo;

    /**
     * Creates new form MenuPrincipal
     *
     * @param tipo
     */
    public MenuPrincipal(String tipo) {
        sis = Sistema.getInstance();
        this.tipo = tipo;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        administrador = new javax.swing.JMenu();
        inserirProduto = new javax.swing.JMenuItem();
        inserirMarca = new javax.swing.JMenuItem();
        inserirUsuario = new javax.swing.JMenuItem();
        listarVendas = new javax.swing.JMenuItem();
        listarVendasDia = new javax.swing.JMenuItem();
        funcionario = new javax.swing.JMenu();
        realizarVenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lojinha DaniLet");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        administrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_gray.png"))); // NOI18N
        administrador.setText("Administrador");

        inserirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        inserirProduto.setText("Inserir Produto");
        inserirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirProdutoActionPerformed(evt);
            }
        });
        administrador.add(inserirProduto);

        inserirMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        inserirMarca.setText("Inserir Marca");
        inserirMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirMarcaActionPerformed(evt);
            }
        });
        administrador.add(inserirMarca);

        inserirUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_add.png"))); // NOI18N
        inserirUsuario.setText("Inserir Usuario");
        inserirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirUsuarioActionPerformed(evt);
            }
        });
        administrador.add(inserirUsuario);

        listarVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table.png"))); // NOI18N
        listarVendas.setText("Listar Vendas");
        listarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarVendasActionPerformed(evt);
            }
        });
        administrador.add(listarVendas);

        listarVendasDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table.png"))); // NOI18N
        listarVendasDia.setText("Listar Vendas no Dia");
        listarVendasDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarVendasDiaActionPerformed(evt);
            }
        });
        administrador.add(listarVendasDia);

        jMenuBar1.add(administrador);

        funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user.png"))); // NOI18N
        funcionario.setText("Funcionario");

        realizarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/basket_add.png"))); // NOI18N
        realizarVenda.setText("Realizar Venda");
        realizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarVendaActionPerformed(evt);
            }
        });
        funcionario.add(realizarVenda);

        jMenuBar1.add(funcionario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LimparJanelas() {
        for (int i = 0; i < jPanel1.countComponents(); i++) {
            jPanel1.remove(i);
        }
    }

    private void ReiniciarJanela() {
        dispose();
        this.setVisible(true);
    }

    private void inserirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirProdutoActionPerformed
        // TODO add your handling code here:
        if (tipo.equals("Administrador")) {
            LimparJanelas();
            CRUDProduto CadUser = new CRUDProduto(new javax.swing.JFrame(), true);
            CadUser.setLocationRelativeTo(null);
            CadUser.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Acesso Negado");
        }
    }//GEN-LAST:event_inserirProdutoActionPerformed

    private void listarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarVendasActionPerformed
        // TODO add your handling code here:
        if (tipo.equals("Administrador")) {
            LimparJanelas();
            listarVenda listar = new listarVenda();
            jPanel1.add(listar);
            listar.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Acesso Negado");
        }
    }//GEN-LAST:event_listarVendasActionPerformed

    private void listarVendasDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarVendasDiaActionPerformed
        // TODO add your handling code here:
        if (tipo.equals("Administrador")) {
            LimparJanelas();
            DataVenda data = new DataVenda(new javax.swing.JFrame(), true);
            data.setLocationRelativeTo(null);
            data.setVisible(true);
            ReiniciarJanela();
            String date = data.getData();
            if (date != null) {
                listarVenda listar = new listarVenda(date);
                jPanel1.add(listar);
                listar.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Acesso Negado");
        }
    }//GEN-LAST:event_listarVendasDiaActionPerformed

    private void realizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarVendaActionPerformed
        // TODO add your handling code here:
        LimparJanelas();
        RealizarVenda venda = new RealizarVenda();
        jPanel1.add(venda);
        venda.setVisible(true);
    }//GEN-LAST:event_realizarVendaActionPerformed

    private void inserirMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirMarcaActionPerformed
        // TODO add your handling code here:
        if (tipo.equals("Administrador")) {
            LimparJanelas();
            CRUDMarca CadUser = new CRUDMarca(new javax.swing.JFrame(), true);
            CadUser.setLocationRelativeTo(null);
            CadUser.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Acesso Negado");
        }

    }//GEN-LAST:event_inserirMarcaActionPerformed

    private void inserirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirUsuarioActionPerformed
        // TODO add your handling code here:
        if (tipo.equals("Administrador")) {
        } else {
            JOptionPane.showMessageDialog(this, "Acesso Negado");
        }
    }//GEN-LAST:event_inserirUsuarioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu administrador;
    private javax.swing.JMenu funcionario;
    private javax.swing.JMenuItem inserirMarca;
    private javax.swing.JMenuItem inserirProduto;
    private javax.swing.JMenuItem inserirUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem listarVendas;
    private javax.swing.JMenuItem listarVendasDia;
    private javax.swing.JMenuItem realizarVenda;
    // End of variables declaration//GEN-END:variables
    private final Sistema sis;
}
