/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loja.ui;

import javax.swing.JOptionPane;
import loja.negocio.Produto;
import loja.negocio.Sistema;

/**
 *
 * @author Daniel
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        sis = Sistema.getInstance();
        sis.limparCarrinho();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        administrador = new javax.swing.JMenu();
        inserirProduto = new javax.swing.JMenuItem();
        listarVendas = new javax.swing.JMenuItem();
        listarVendasDia = new javax.swing.JMenuItem();
        buscarVenda = new javax.swing.JMenuItem();
        funcionario = new javax.swing.JMenu();
        realizarVenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lojinha DaniLet");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        administrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_gray.png"))); // NOI18N
        administrador.setText("Administrador");

        inserirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        inserirProduto.setText("Inserir Produto");
        inserirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirProdutoActionPerformed(evt);
            }
        });
        administrador.add(inserirProduto);

        listarVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table.png"))); // NOI18N
        listarVendas.setText("Listar Vendas");
        listarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarVendasActionPerformed(evt);
            }
        });
        administrador.add(listarVendas);

        listarVendasDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/table.png"))); // NOI18N
        listarVendasDia.setText("Listar Vendas no Dia");
        listarVendasDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarVendasDiaActionPerformed(evt);
            }
        });
        administrador.add(listarVendasDia);

        buscarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/zoom.png"))); // NOI18N
        buscarVenda.setText("Buscar Venda");
        buscarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarVendaActionPerformed(evt);
            }
        });
        administrador.add(buscarVenda);

        jMenuBar1.add(administrador);

        funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user.png"))); // NOI18N
        funcionario.setText("Funcionario");

        realizarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/basket_add.png"))); // NOI18N
        realizarVenda.setText("Realizar Venda");
        realizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarVendaActionPerformed(evt);
            }
        });
        funcionario.add(realizarVenda);

        jMenuBar1.add(funcionario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LimparJanelas() {
        for (int i = 0; i < jPanel1.countComponents(); i++) {
            jPanel1.remove(i);
        }
    }

    private void ReiniciarJanela() {
        dispose();
        this.setVisible(true);
    }

    private void inserirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirProdutoActionPerformed
        // TODO add your handling code here:
        LimparJanelas();
        CRUDProduto CadUser = new CRUDProduto(new javax.swing.JFrame(), true);
        CadUser.setLocationRelativeTo(null);
        CadUser.setVisible(true);
    }//GEN-LAST:event_inserirProdutoActionPerformed

    private void buscarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarVendaActionPerformed
        // TODO add your handling code here:
        LimparJanelas();
        CodigoBuscar codBus = new CodigoBuscar(new javax.swing.JFrame(), true);
        codBus.setLocationRelativeTo(null);
        codBus.setVisible(true);
        ReiniciarJanela();
        BuscarVenda listar = new BuscarVenda(codBus.getCodigo());
        jPanel1.add(listar);
        listar.setVisible(true);
    }//GEN-LAST:event_buscarVendaActionPerformed

    private void listarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarVendasActionPerformed
        // TODO add your handling code here:
        LimparJanelas();
        listarVenda listar = new listarVenda();
        jPanel1.add(listar);
        listar.setVisible(true);
    }//GEN-LAST:event_listarVendasActionPerformed

    private void listarVendasDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarVendasDiaActionPerformed
        // TODO add your handling code here:
        LimparJanelas();
        DataVenda data = new DataVenda(new javax.swing.JFrame(), true);
        data.setLocationRelativeTo(null);
        data.setVisible(true);
        ReiniciarJanela();
        String date = data.getData();
        if(date != null){
            listarVenda listar = new listarVenda(date);
            jPanel1.add(listar);
            listar.setVisible(true);
        }
    }//GEN-LAST:event_listarVendasDiaActionPerformed

    private void realizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarVendaActionPerformed
        // TODO add your handling code here:
        LimparJanelas();
        RealizarVenda venda = new RealizarVenda();
        jPanel1.add(venda);
        venda.setVisible(true);
    }//GEN-LAST:event_realizarVendaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu administrador;
    private javax.swing.JMenuItem buscarVenda;
    private javax.swing.JMenu funcionario;
    private javax.swing.JMenuItem inserirProduto;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem listarVendas;
    private javax.swing.JMenuItem listarVendasDia;
    private javax.swing.JMenuItem realizarVenda;
    // End of variables declaration//GEN-END:variables
    private final Sistema sis;
}
